version: "3.9"
services:
  address:
    container_name: person_service
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=person_service
      - POSTGRES_USER=Mardali
      - POSTGRES_PASSWORD=Mardali
    volumes:
      - db:/var/lib/postgresql/personService
    ports:
      - "5434:5432"
    command: -p 5432
volumes:
  db: