version: "3.9"
services:
  address:
    container_name: car_service
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=car_service
      - POSTGRES_USER=Mardali
      - POSTGRES_PASSWORD=Mardali
    volumes:
      - db:/var/lib/postgresql/carService
    ports:
      - "5431:5432"
    command: -p 5432
volumes:
  db: