server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/house_service
    username: Mardali
    password: Mardali
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
