create table houses
(
    id        int4 generated by default as identity,
    address   varchar(100) not null,
    area      double precision,
    primary key (id)
);
INSERT INTO houses (address, area)
VALUES ('ул. Ленина, 10', 120.5),
       ('ул. Пушкина, 5', 150.2);
