version: "3.9"
services:
  address:
    container_name: city
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=city
      - POSTGRES_USER=Mardali
      - POSTGRES_PASSWORD=Mardali
    volumes:
      - db:/var/lib/postgresql/city
    ports:
      - "5432:5432"
    command: -p 5432
volumes:
  db: