create table persons
(
    id          int4 generated by default as identity,
    name        varchar(100) not null,
    surname     varchar(100) not null,
    birth_date  date         not null,
    gender      varchar(10)  not null,
    passport_id int4,
    primary key (id)
);
insert into persons(name, surname, birth_date, gender, passport_id)
values ('Владимир', 'Попович', '1985-05-08','мужской', 1),
       ('Дмитрий', 'Полянский', '1986-11-07', 'мужской', 2),
       ('Ольга', 'Андреева', '1987-08-30','женский', 3);

create table passport
(
    id            int4 generated by default as identity,
    series_number INT4 NOT NULL,
    issue_date    DATE NOT NULL,
    primary key (id)
);
insert into passport(series_number, issue_date)
values (123456, '2022-01-01'),
       (145456, '2022-01-07'),
       (654321, '2022-02-01');
