create table persons
(
    id          int4 generated by default as identity,
    name        varchar(100) not null,
    surname     varchar(100) not null,
    birth_date  date         not null,
    passport_id int4,
    primary key (id)
);
insert into persons(name, surname, birth_date, passport_id)
values ('Владимир', 'Попович', '1985-05-08', 1),
       ('Дмитрий', 'Полянский', '1986-11-07', 2),
       ('Ольга', 'Андреева', '1987-08-30', 3);

create table cars
(
    id           int4 generated by default as identity,
    brand        varchar(100) not null,
    model        varchar(100) not null,
    number       varchar(100) not null,
    release_year int4         not null,
    person_id    integer,
    foreign key (person_id) references persons (id),
    primary key (id)
);
insert into cars(brand, model, number, release_year, person_id)
VALUES ('BMW', 'X5', 'С545СС777', 2020, 1),
       ('Audi', 'A4', 'Ф323МР77', 2019, 2);

create table houses
(
    id        int4 generated by default as identity,
    address   varchar(100) not null,
    area      double precision,
    person_id integer,
    foreign key (person_id) references persons (id),
    primary key (id)
);
INSERT INTO houses (address, area, person_id)
VALUES ('ул. Ленина, 10', 120.5, 1),
       ('ул. Пушкина, 5', 150.2, 3);

CREATE TABLE owner_house
(
    person_id int4 not null,
    house_id  int4 not null,

    PRIMARY KEY (person_id, house_id)
);

INSERT INTO owner_house (person_id, house_id)
VALUES (2, 1),
       (1, 2);

create table passport
(
    id            int4 generated by default as identity,
    series_number INT4 NOT NULL,
    issue_date    DATE NOT NULL,
    primary key (id)
);
insert into passport(series_number, issue_date)
values (123456, '2022-01-01'),
       (145456, '2022-01-07'),
       (654321, '2022-02-01');